services:
  mrsm-compose:
    build:
      context: "./"
      dockerfile: "./docker/Dockerfile"

    ### Override the `bootstrap.sh` entrypoint for interactive development and testing.
    entrypoint: ["/app/docker/sleep_forever.sh"]

    # environment:
      # MRSM_STRAVA_MAIN: $MRSM_STRAVA_MAIN

    network_mode: "host"
    volumes:
      - "./:/app"
      - "mrsm-root:/meerschaum"
    init: true
    tty: true

volumes:
  mrsm-root:
