services:
  mrsm-compose:
    build:
      context: "./"
      dockerfile: "./docker/Dockerfile"

    ### Override the `bootstrap.sh` entrypoint for interactive development and testing.
    entrypoint: ["/app/docker/sleep_forever.sh"]

    environment:
      MRSM_API_BMEARES: "$MRSM_API_BMEARES"

    network_mode: "host"
    volumes:
      - "./:/app"
      - "mrsm-root:/meerschaum"
    init: true
    tty: true

volumes:
  mrsm-root:
