root_dir: "/meerschaum"
project_name: "strava"

pipes:
  - connector: "plugin:strava"
    metric: "activities"
    columns:
      datetime: "start_date"
      activity_id: "id"

config:
  meerschaum:
    instance: "api:bmeares"
    connectors:
      sql:
        main: MRSM{meerschaum:connectors:sql:main}
      api:
        bmeares: MRSM{meerschaum:connectors:api:bmeares}

environment: {}
