root_dir: "/meerschaum"
project_name: "strava"

sync:
  pipes:
    - connector: "plugin:strava"
      metric: "activities"
      location: "bmeares"
      columns:
        datetime: "start_date"
        upload_id: "upload_id"

config:
  meerschaum:
    instance: "sql:main"
    connectors:
      sql:
        main: MRSM{meerschaum:connectors:sql:main}
      # strava:
        # main: MRSM{meerschaum:connectors:strava:main}

environment: {}
